blank_issues_enabled: false
contact_links:
  - name: "\U0001F46A Prismic Community Forum"
    url: https://community.prismic.io
    about: Ask a question about the package or raise an issue directly related to Prismic. You will usually get support there more quickly!
